/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as interfaces from "./interfaces";
export type { interfaces };
export type { VRFConsumerBase } from "./VRFConsumerBase";
export type { VRFConsumerBaseV2 } from "./VRFConsumerBaseV2";
